export const PRODUCT_REPOSITORY_TOKEN = Symbol('PRODUCT_REPOSITORY');

export const PRODUCT_PRICE_REPOSITORY_TOKEN = Symbol(
  'PRODUCT_PRICE_REPOSITORY',
);

export const PRODUCT_RESOURCE_REPOSITORY_TOKEN = Symbol(
  'PRODUCT_RESOURCE_REPOSITORY',
);

export const RESOURCE_REPOSITORY_TOKEN = Symbol('RESOURCE_REPOSITORY');

export const DISCOUNT_REPOSITORY_TOKEN = Symbol('DISCOUNT_REPOSITORY');
